sources:
  - name: OpenAI
    url: https://www.openai.com/blog/rss.xml
    category: openai

  - name: Hacker News
    url: https://hnrss.org/best
    category: hacker_news

  - name: Google AI
    url: https://blog.google/technology/ai/rss/
    category: google_ai

  - name: Hugging Face
    url: https://huggingface.co/blog/feed.xml
    category: hugging_face

  - name: MIT Technology Review AI
    url: https://www.technologyreview.com/topic/artificial-intelligence/feed/
    category: mit_technology_ai

  - name: The Decoder
    url: https://the-decoder.com/feed/
    category: the_decoder

  - name: VentureBeat AI
    url: https://venturebeat.com/category/ai/feed
    category: venturebeat_ai

  - name: V2EX
    url: https://rsshub.rssforever.com/v2ex/topics/hot
    category: v2ex

  - name: GitHub
    url: https://github.blog/feed/
    category: github

  - name: Vue Blog
    url: https://blog.vuejs.org/feed.rss
    category: vue_blog

  - name: JavaScript Weekly
    url: https://cprss.s3.amazonaws.com/javascriptweekly.com.xml
    category: javascript_weekly

  - name: Stack Overflow Blog
    url: https://stackoverflow.blog/feed
    category: stackoverflow_blog

  - name: BBC News
    url: https://feeds.bbci.co.uk/news/rss.xml
    category: bbc_news

  - name: 联合早报
    url: https://plink.anyfeeder.com/zaobao/realtime/china
    category: zaobao_china

  - name: 36氪
    url: https://36kr.com/feed
    category: 36kr

  - name: 华尔街见闻
    url: https://cn.wsj.com/rss-news-and-feeds/zh-hans
    category: wsj

  - name: Financial Times 中文网
    url: https://www.ftchinese.com/rss/news
    category: ft_chinese

  - name: InfoQ
    url: https://plink.anyfeeder.com/infoq/recommend
    category: infoq

  - name: 掘金
    url: https://rsshub.bestblogs.dev/juejin/trending/all/weekly
    category: juejin

  - name: 雪球
    url: https://xueqiu.com/hots/topic/rss
    category: xueqiu

  - name: 财联社
    url: https://rsshub.rssforever.com/cls/telegraph
    category: cls
