"""add ingest_date to news_items

Revision ID: c0804ab220a9
Revises: f6bbd64101dc
Create Date: 2026-04-20 11:27:10.817284

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c0804ab220a9'
down_revision: Union[str, Sequence[str], None] = 'f6bbd64101dc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('news_items', sa.Column('ingest_date', sa.Date(), server_default=sa.text('CURRENT_DATE'), nullable=False))
    op.create_index(op.f('ix_news_items_ingest_date'), 'news_items', ['ingest_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_news_items_ingest_date'), table_name='news_items')
    op.drop_column('news_items', 'ingest_date')
    # ### end Alembic commands ###
